In [1]:
import requests
import pandas as pd

In [2]:
credito = pd.read_csv("Credit.csv")
credito

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6,'critical/other existing credit',radio/tv,1169,'no known savings',>=7,4,'male single',none,...,'real estate',67,none,own,2,skilled,1,yes,yes,good
1,0<=X<200,48,'existing paid',radio/tv,5951,<100,1<=X<4,2,'female div/dep/mar',none,...,'real estate',22,none,own,1,skilled,1,none,yes,bad
2,'no checking',12,'critical/other existing credit',education,2096,<100,4<=X<7,2,'male single',none,...,'real estate',49,none,own,1,'unskilled resident',2,none,yes,good
3,<0,42,'existing paid',furniture/equipment,7882,<100,4<=X<7,2,'male single',guarantor,...,'life insurance',45,none,'for free',1,skilled,2,none,yes,good
4,<0,24,'delayed previously','new car',4870,<100,1<=X<4,3,'male single',none,...,'no known property',53,none,'for free',2,skilled,2,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,'no checking',12,'existing paid',furniture/equipment,1736,<100,4<=X<7,3,'female div/dep/mar',none,...,'real estate',31,none,own,1,'unskilled resident',1,none,yes,good
996,<0,30,'existing paid','used car',3857,<100,1<=X<4,4,'male div/sep',none,...,'life insurance',40,none,own,1,'high qualif/self emp/mgmt',1,yes,yes,good
997,'no checking',12,'existing paid',radio/tv,804,<100,>=7,4,'male single',none,...,car,38,none,own,1,skilled,1,none,yes,good
998,<0,45,'existing paid',radio/tv,1845,<100,1<=X<4,4,'male single',none,...,'no known property',23,none,'for free',1,skilled,1,yes,yes,bad
999,0<=X<200,45,'critical/other existing credit','used car',4576,100<=X<500,unemployed,3,'male single',none,...,car,27,none,own,1,skilled,1,none,yes,good

In [3]:
for col in credito.columns:
    if credito[col].dtype == 'object':
        credito[col] = credito[col].astype('category').cat.codes

In [11]:
dados = credito.iloc[0:10, :20].to_json(orient='records')
dados

'[{"checking_status":2,"duration":6,"credit_history":1,"purpose":7,"credit_amount":1169,"savings_status":0,"employment":3,"installment_commitment":4,"personal_status":3,"other_parties":2,"residence_since":4,"property_magnitude":2,"age":67,"other_payment_plans":1,"housing":1,"existing_credits":2,"job":3,"num_dependents":1,"own_telephone":1,"foreign_worker":1},{"checking_status":1,"duration":48,"credit_history":3,"purpose":7,"credit_amount":5951,"savings_status":3,"employment":0,"installment_commitment":2,"personal_status":0,"other_parties":2,"residence_since":2,"property_magnitude":2,"age":22,"other_payment_plans":1,"housing":1,"existing_credits":1,"job":3,"num_dependents":1,"own_telephone":0,"foreign_worker":1},{"checking_status":0,"duration":12,"credit_history":1,"purpose":4,"credit_amount":2096,"savings_status":3,"employment":1,"installment_commitment":2,"personal_status":3,"other_parties":2,"residence_since":3,"property_magnitude":2,"age":49,"other_payment_plans":1,"housing":1,"existing_credits":1,"job":2,"num_dependents":2,"own_telephone":0,"foreign_worker":1},{"checking_status":2,"duration":42,"credit_history":3,"purpose":5,"credit_amount":7882,"savings_status":3,"employment":1,"installment_commitment":2,"personal_status":3,"other_parties":1,"residence_since":4,"property_magnitude":0,"age":45,"other_payment_plans":1,"housing":0,"existing_credits":1,"job":3,"num_dependents":2,"own_telephone":0,"foreign_worker":1},{"checking_status":2,"duration":24,"credit_history":2,"purpose":1,"credit_amount":4870,"savings_status":3,"employment":0,"installment_commitment":3,"personal_status":3,"other_parties":2,"residence_since":4,"property_magnitude":1,"age":53,"other_payment_plans":1,"housing":0,"existing_credits":2,"job":3,"num_dependents":2,"own_telephone":0,"foreign_worker":1},{"checking_status":0,"duration":36,"credit_history":3,"purpose":4,"credit_amount":9055,"savings_status":0,"employment":0,"installment_commitment":2,"personal_status":3,"other_parties":2,"residence_since":4,"property_magnitude":1,"age":35,"other_payment_plans":1,"housing":0,"existing_credits":1,"job":2,"num_dependents":2,"own_telephone":1,"foreign_worker":1},{"checking_status":0,"duration":24,"credit_history":3,"purpose":5,"credit_amount":2835,"savings_status":2,"employment":3,"installment_commitment":3,"personal_status":3,"other_parties":2,"residence_since":4,"property_magnitude":0,"age":53,"other_payment_plans":1,"housing":1,"existing_credits":1,"job":3,"num_dependents":1,"own_telephone":0,"foreign_worker":1},{"checking_status":1,"duration":36,"credit_history":3,"purpose":2,"credit_amount":6948,"savings_status":3,"employment":0,"installment_commitment":2,"personal_status":3,"other_parties":2,"residence_since":2,"property_magnitude":3,"age":35,"other_payment_plans":1,"housing":2,"existing_credits":1,"job":0,"num_dependents":1,"own_telephone":1,"foreign_worker":1},{"checking_status":0,"duration":12,"credit_history":3,"purpose":7,"credit_amount":3059,"savings_status":4,"employment":1,"installment_commitment":2,"personal_status":1,"other_parties":2,"residence_since":4,"property_magnitude":2,"age":61,"other_payment_plans":1,"housing":1,"existing_credits":1,"job":2,"num_dependents":1,"own_telephone":0,"foreign_worker":1},{"checking_status":1,"duration":30,"credit_history":1,"purpose":1,"credit_amount":5234,"savings_status":3,"employment":4,"installment_commitment":4,"personal_status":2,"other_parties":2,"residence_since":2,"property_magnitude":3,"age":28,"other_payment_plans":1,"housing":1,"existing_credits":2,"job":0,"num_dependents":1,"own_telephone":0,"foreign_worker":1}]'

In [24]:
#EXECUTE mlflow models serve --model-uri runs:/{model id}/{experiment name} -p {port number} --env-manager=local
pred = requests.post(url='http://localhost:2345/invocations', headers={'Content-Type': 'application/json'}, data=dados)

In [25]:
pred.text

'[1, 0, 1, 1, 0, 1, 1, 1, 1, 0]'